name: Intel
on:
  push:
    branches:
    - develop
  pull_request:
    branches:
    - develop

jobs:
  Intel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compilers: ["oneapi", "classic"]

    steps:

    - name: "Install Intel"
      uses: NOAA-EMC/ci-install-intel-toolkit@develop
      with:
        install-mpi: true
        mpi-wrapper-setup: ${{ matrix.compilers }}

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: develop
        w3emc-version: develop
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
        nemsio-version: develop
        key-prefix: Intel-
        key-suffix: -1

    - name: checkout
      uses: actions/checkout@v4
      with: 
        path: nemsiogfs

    - name: build
      run: |
        cmake -S nemsiogfs -B nemsiogfs/build -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-nemsio"
        cmake --build nemsiogfs/build --parallel 2 --verbose
    
    - name: test
      run: |
        ctest --test-dir nemsiogfs/build --rerun-failed --output-on-failure
