name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        openmp: [ON, OFF]
    env:
      FC: gfortran-9
      CC: gcc-9

    steps:

    - name: install-mpi
      run: |
        sudo apt-get install libmpich-dev

    - name: checkout-bacio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-bacio
        path: bacio
        ref: develop

    - name: build-bacio
      run: |
        cd bacio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/bacio
        make -j2
        make install

    - name: checkout-sp
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sp
        path: sp
        ref: develop

    - name: build-sp
      run: |
        cd sp
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/sp
        make -j2
        make install

    - name: checkout-w3emc
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-w3emc
        path: w3emc
        ref: develop

    - name: build-w3emc
      run: |
        cd w3emc
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/w3emc
        make -j2
        make install          

    - name: checkout-sigio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-sigio
        path: sigio
        ref: develop

    - name: build-sigio
      run: |
        cd sigio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/sigio
        make -j2
        make install

    - name: checkout-nemsio
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-nemsio
        path: nemsio
        ref: develop

    - name: build-nemsio
      run: |
        cd nemsio
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/nemsio -DCMAKE_PREFIX_PATH=~
        make -j2
        make install

    - name: checkout-ip
      uses: actions/checkout@v2
      with:
        repository: NOAA-EMC/NCEPLIBS-ip
        path: ip
        ref: develop

    - name: build-ip
      run: |
        cd ip
        mkdir build
        cd build
        cmake .. -DCMAKE_INSTALL_PREFIX=~/ip -DCMAKE_PREFIX_PATH=~
        make -j2
        make install  

    - name: checkout-nemsiogfs
      uses: actions/checkout@v2
      with: 
        path: nemsiogfs
        submodules: true

    - name: build-nemsiogfs
      run: |
        cd nemsiogfs
        mkdir build 
        cd build
        cmake .. -DOPENMP=${{ matrix.openmp }}  -DCMAKE_PREFIX_PATH="~/"
        make -j2
    
    - name: test-nemsiogfs
      run: |
        cd $GITHUB_WORKSPACE/nemsiogfs/build
        make test

