name: Build and Test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        openmp: [ON, OFF]
    env:
      FC: gfortran-11
      CC: gcc-11

    steps:

    - name: install-mpi
      run: |
        sudo apt-get install libmpich-dev

    - name: "Build dependencies"
      uses: NOAA-EMC/ci-build-nceplibs@develop
      with:
        bacio-version: develop
        w3emc-version: develop
        w3emc-cmake-args: -DBUILD_WITH_BUFR=OFF
        nemsio-version: develop
        key-suffix: -1

    - name: checkout-nemsiogfs
      uses: actions/checkout@v4
      with: 
        path: nemsiogfs

    - name: build-nemsiogfs
      run: |
        cmake -S nemsiogfs -B nemsiogfs/build -DOPENMP=${{ matrix.openmp }} -DCMAKE_PREFIX_PATH="$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-bacio;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-w3emc;$GITHUB_WORKSPACE/nceplibs/NCEPLIBS-nemsio"
        cmake --build nemsiogfs/build --parallel 2 --verbose
    
    - name: test-nemsiogfs
      run: ctest --test-dir nemsiogfs/build --output-on-failure
